apiVersion: v1
kind: Service
metadata:
  name: guestbook-svc
  namespace: fuze
  labels:
    app: guestbook
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 8999
    targetPort: 80
  selector:
    app: guestbook
    tier: frontend
